---
### geoschem_config.yml: GEOS-Chem Runtime configuration options.
### Customized for simulations using the KPP "Hg" mechanism.
###
### NOTE: Add quotes around nitrogen oxide ('NO'), because YAML
### parsers will confuse this with a negative "no" value.

#============================================================================
# Simulation settings
#============================================================================
simulation:
  name: Hg
  start_date: [20190101, 000000]
  end_date: [20190201, 000000]
  root_data_dir: /net/geoschem/data/gcgrid/data/ExtData/
  met_field: MERRA2
  species_database_file: ./species_database.yml
  species_metadata_output_file: OutputDir/geoschem_species_metadata.yml
  verbose:
    activate: false
    on_cores: root       # Allowed values: root all
  use_gcclassic_timers: false

#============================================================================
# Grid settings
#============================================================================
grid:
  resolution: 2.0x2.5
  number_of_levels: 47
  longitude:
    range: [-180.0, 180.0]
    center_at_180: true 
  latitude:
    range: [-90.0, 90.0]
    half_size_polar_boxes: true 
  nested_grid_simulation:
    activate: false
    buffer_zone_NSEW: [0, 0, 0, 0]

#============================================================================
# Timesteps settings
#============================================================================
timesteps:
  transport_timestep_in_s: 600
  chemistry_timestep_in_s: 1200

#============================================================================
# Settings for GEOS-Chem operations
#============================================================================
operations:

  chemistry:
    activate: true

  convection:
    activate: true

  dry_deposition:
    activate: true
    diag_alt_above_sfc_in_m: 10

  pbl_mixing:
     activate: true
     use_non_local_pbl: true 

  photolysis:
    activate: true
    input_directories:
      fastjx_input_dir: /net/geoschem/data/gcgrid/data/ExtData//CHEM_INPUTS/FAST_JX/v2022-10-Hg/
      cloudj_input_dir: /net/geoschem/data/gcgrid/data/ExtData//CHEM_INPUTS/CLOUD_J/v2023-11-Hg/
    overhead_O3:
      use_online_O3_from_model: true 
      use_column_O3_from_met: true
      use_TOMS_SBUV_O3: false

  transport:
    gcclassic_tpcore:                 # GEOS-Chem Classic only
      activate: true                  # GEOS-Chem Classic only
      fill_negative_values: true      # GEOS-Chem Classic only
      iord_jord_kord: [3, 3, 7]       # GEOS-Chem Classic only
    transported_species:
      -  Hg0
      -  HgBr
      -  HgBrNO2
      -  HgBrHO2
      -  HgBrBrO
      -  HgBrClO
      -  HgBrOH
      -  HgBr2
      -  HgCl
      -  HgClNO2
      -  HgClHO2
      -  HgClClO
      -  HgClBrO
      -  HgClBr
      -  HgClOH
      -  HgOH
      -  HgOHNO2
      -  HgOHHO2
      -  HgOHClO
      -  HgOHBrO
      -  HgOHOH
      -  HgCl2
      -  Hg2ClP
      -  Hg2ORGP
      -  Hg2STRP

  wet_deposition:
    activate: true
    
#============================================================================
# Settings specific to the Hg simulation
#============================================================================
Hg_simulation_options:

  sources:
    use_dynamic_ocean_Hg: false
    use_preindustrial_Hg: false
    use_arctic_river_Hg: true

  chemistry:
    tie_HgIIaq_reduction_to_UVB: true

  # NOTE: GTMM is currently, we look to the Hg & POPs community
  # to take the lead in restoring it. (bmy, 04 Apr 2022)
  GTMM_soil_model:
    activate: false
    restart_file: N/A

#============================================================================
# Settings for diagnostics (other than HISTORY and HEMCO)
#============================================================================
extra_diagnostics:

  obspack:
    activate: false
    quiet_logfile_output: false
    input_file: ./obspack_co2_1_OCO2MIP_2018-11-28.YYYYMMDD.nc
    output_file: ./OutputDir/GEOSChem.ObsPack.YYYYMMDD_hhmmz.nc4
    output_species:
      - Hg0

  planeflight:
    activate: false
    flight_track_file: Planeflight.dat.YYYYMMDD
    output_file: plane.log.YYYYMMDD